### ISSUE TITLE
How can I download 5000 snapshots at the redshift zero at once?

### ISSUE THREAD

**Issue by WangYun1995** [franciscovillaescusa/Quijote-simulations#12]
Hi,
I want to know how to download multiple snapshots of fiducial cosmology at the redshift zero at once. 
Do you have any tips?
Thank you!

**Comment by franciscovillaescusa** [comment]
Hi,

Thanks for the query. For this, I would recommend using the Command Line Interface of globus. Take a look here:
https://quijote-simulations.readthedocs.io/en/latest/access.html#globus
To see examples of how to deal with those situations.

Also you can also use binder to access and manipulate the data without downloading a single byte. You can do the analysis and then download just the data you generate from the postprocessing. Take a look here:
https://quijote-simulations.readthedocs.io/en/latest/access.html#binder

Let me know if this is not clear or you still have doubts.

Best,

Francisco

**Comment by WangYun1995** [comment]
@franciscovillaescusa I will try following your advice! ^^. 0.
