### ISSUE TITLE
Can not find individual parameter variation simulations of f(R)

### ISSUE THREAD

**Issue by Lxion0553** [franciscovillaescusa/Quijote-simulations#13]
Hi!
The table in the document->structure and types says there are fR_p, fR_pp, fR_ppp simulations, but I can not find through globus.
Are they moved to another place? Where can I find them?
Thank you!

**Comment by franciscovillaescusa** [comment]
Hi,

These simulations are not public yet (they will be soon). Take a look here in case you want to use them:
https://quijote-simulations.readthedocs.io/en/latest/mg.html

Best

Francisco
